#!/usr/bin/env bash
set -euo pipefail

fail() { echo "ERROR: $*" >&2; exit 2; }

readonly repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
readonly fixture="${repo_root}/legacy/product-service/src/test/resources/product-read-baseline/db-permissions/cases.json"
readonly manifest="${repo_root}/legacy/product-service/src/test/resources/product-read-baseline/manifest.json"
readonly expected_ids='["DB-DENY-ALTER-001","DB-DENY-CREATE-001","DB-DENY-DELETE-001","DB-DENY-DROP-001","DB-DENY-INSERT-001","DB-DENY-TRUNCATE-001","DB-DENY-UPDATE-001","DB-READ-CONNECT-001","DB-READ-GET-001","DB-READ-LIST-001"]'

[[ -f "${fixture}" ]] || fail "Missing database-permission fixture: ${fixture}"
jq -e --argjson expected "${expected_ids}" '
  .schemaVersion == 1 and .fixtureId == "DB-PERMISSIONS-001" and .provenance == "synthetic-isolated"
  and ([.cases[].id] | sort) == $expected
  and ([.cases[] | select(.operationClass == "read")] | length == 3)
  and ([.cases[] | select(.operationClass == "dml")] | length == 4)
  and ([.cases[] | select(.operationClass == "ddl")] | length == 3)
  and ([.expectedObservations[].id] | sort) == (["DB-ROLE-BASELINE-001"] + $expected | sort)
  and ([.expectedObservations[] | select(.status == "succeeded")] | length == 3)
  and ([.expectedObservations[] | select(.status == "denied")] | length == 7)
  and ([.expectedObservations[] | select(.status == "denied") | .sqlState] | all(. == "42501"))
  and .roleSpecification.attributes == {
    login: true, superuser: false, createDatabase: false, createRole: false,
    inherit: false, replication: false, bypassRls: false
  }
  and .roleSpecification.databasePrivileges == ["CONNECT"]
  and .roleSpecification.schemaPrivileges == ["USAGE"]
  and .roleSpecification.tablePrivileges == ["SELECT"]
  and .roleSpecification.memberOfRoles == []
  and (.expectedObservations[] | select(.id == "DB-ROLE-BASELINE-001")
    | .ownsDatabase == false and .ownsSchema == false and .ownsTable == false
    and .memberOfRoleCount == 0
    and .publicTableGrantCount == 0
    and .publicDefaultTableGrantCount == 0
    and .candidateDefaultTableGrantCount == 0
    and .sequenceCount == 0)
  and .safety.setupIdentityDistinctFromCandidate == true
  and .safety.sharedEnvironmentMutation == false
  and .safety.dataAndSchemaIdentityRequiredUnchanged == true
  and .safety.credentialRetained == false
' "${fixture}" >/dev/null || fail "Invalid database-permission fixture."

jq -e '
  ([.scenarios[] | select(.id == "DB-READ-001" or .id == "DB-DML-DENY-001" or .id == "DB-DDL-DENY-001")
    | select(.status == "captured" and .fixture == "db-permissions/cases.json")] | length) == 3
' "${manifest}" >/dev/null || fail "Manifest database-permission scenarios are not linked to the fixture."

if grep -Eq 'password|secret|token' "${fixture}"; then
  jq -e '[.. | strings | select(test("password|secret|token"; "i"))]
    | all(. == "runtime-generated by isolated admin fixture; no value retained")' "${fixture}" >/dev/null || \
    fail "Database-permission fixture contains credential-shaped metadata."
fi
echo "Validated isolated Product database-permission fixture."
