coverage:
  range: "50...75"
  status:
    project:
      default:
        target: 75%
        threshold: 0%
        flags:
          - product-service
    patch:
      default:
        informational: true

flags:
  product-service:
    paths:
      - services/product-service/
    carryforward: false

ignore:
  - "services/product-service/gen/**"
  - "services/product-service/internal/postgres/dbgen/**"
  - "services/product-service/internal/testing/**"
