version: '2'

services:
  jsreport:
    image: jsreport/jsreport
    container_name: jsreport
    hostname: jsreport
    ports:
      - 5488:5488
  consul:
    image: consul
    container_name: consul
    hostname: consul
    ports:
      - 8500:8500
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    hostname: zipkin
    ports:
      - 9411:9411
  mongo:
    image: mongo
    container_name: mongo
    hostname: mongo
    ports:
      - 27017:27017
  kafkaserver:
    image: "spotify/kafka:latest"
    container_name: kafka
    hostname: kafkaserver
    ports:
      - 2181:2181
      - 9092:9092
    environment:
      ADVERTISED_HOST: kafkaserver
      ADVERTISED_PORT: 9092
  kafka_manager:
    image: "mzagar/kafka-manager-docker:1.3.3.4"
    container_name: kafkamanager
    hostname: kafkamanager
    ports:
      - 9000:9000
    environment:
      ZK_HOSTS: "kafkaserver:2181"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.2
    container_name: elasticsearch
    environment:
    - cluster.name=docker-cluster
    - bootstrap.memory_lock=true
    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
    - 9200:9200
