
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-exporter
  namespace: qa-data
  labels:
    app: elasticsearch-exporter
spec:
  ports:
    - name: metrics
      port: 9114
      targetPort: 9114
      protocol: TCP
  selector:
    app: elasticsearch-exporter
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch-exporter
  namespace: qa-data
  labels:
    app: elasticsearch-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch-exporter
  template:
    metadata:
      labels:
        app: elasticsearch-exporter
    spec:
      containers:
        - name: elasticsearch-exporter
          image: quay.io/prometheuscommunity/elasticsearch-exporter:v1.8.0
          args:
            - '--es.uri=https://qa-elasticsearch-es-http:9200'
            - '--es.all'
            - '--es.indices'
            - '--es.indices_settings'
            - '--es.shards'
            - '--es.timeout=30s'
            - '--es.ssl-skip-verify'
          env:
            - name: ES_USERNAME
              value: "elastic"
            - name: ES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: qa-elasticsearch-es-elastic-user
                  key: elastic
          ports:
            - containerPort: 9114
              name: metrics
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
          livenessProbe:
            httpGet:
              path: /health
              port: 9114
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 9114
            initialDelaySeconds: 10
            periodSeconds: 5
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: elasticsearch-exporter
  namespace: qa-data
  labels:
    app: elasticsearch-exporter
    release: qa-prometheus
spec:
  selector:
    matchLabels:
      app: elasticsearch-exporter
  endpoints:
    - port: metrics
      interval: 30s
      path: /metrics