apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-authsvc
  namespace: qa-data
spec:
  instances: 2
  imageName: ghcr.io/cloudnative-pg/postgresql:17
  storage:
    size: 1Gi
  bootstrap:
    initdb:
      database: authsvc
      owner: authsvc
      secret:
        name: postgres-authsvc-creds-qa
  resources:
    requests:
      cpu: "250m"
      memory: "512Mi"
    limits:
      cpu: "500m"
      memory: "1Gi"
  monitoring:
    enablePodMonitor: true
