# Values for Bitnami PostgreSQL wrapper chart tailored for QA on local multi-node K3s with 3 LXD VMs.
# Although QA is local, it emulates production-like topology with replication.
postgresql:
  # Use replication for QA to validate HA patterns on multi-node
  architecture: replication

  primary:
    persistence:
      enabled: true
      size: 10Gi
      storageClass: "local-path"  # K3s local-path provisioner
    resources:
      requests:
        memory: "512Mi"
        cpu: "500m"
      limits:
        memory: "1Gi"
        cpu: "1000m"

  # Enable 2 read replicas for QA testing
  readReplicas:
    replicaCount: 2
    resources:
      requests:
        memory: "256Mi"
        cpu: "250m"
      limits:
        memory: "512Mi"
        cpu: "500m"

  auth:
    # Use the secret created by the 'postgres-create-secret' Makefile target.
    existingSecret: "qa-postgres-secret"
    # Explicitly define the key within that secret.
    secretKeys:
      postgresPasswordKey: "postgres-password"
    # Although this is a production-like environment, using the default 'postgres'
    # database is acceptable for this project's QA purposes. This value is required
    # for the metrics exporter to connect to a database.
    database: "postgres"

  # Enable metrics and ServiceMonitor for QA clusters with Prometheus installed
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
