apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/minio/operator?ref=v7.1.1

patches:
  - target:
      kind: Deployment
      name: minio-operator
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1