# Values for Bitnami PostgreSQL wrapper chart tailored for local Kind (single-node) cluster.
# Both environments are considered local; this one is minimal for developer laptops.
mongodb:
  image:
    registry: docker.io
    repository: bitnami/mongodb
    tag: "8.0.13"
    pullPolicy: Always
  architecture: standalone
  # Enable volume permissions for non-root user (recommended)
  volumePermissions:
    enabled: true
  securityContext:
    runAsUser: 0
  persistence:
    enabled: true
    size: 2Gi
    storageClass: "standard"
  resources:
    requests:
      memory: "256Mi"
      cpu: "250m"
    limits:
      memory: "512Mi"
      cpu: "500m"
  replicaSet:
    enabled: false
  auth:
    enabled: true
    rootPassword: "mongodb"
    usePasswordSecret: false
  metrics:
    enabled: false
  serviceMonitor:
    enabled: false
