apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: local-dev-postgres-productsvc
  namespace: local-dev-all
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:17
  storage:
    size: 1Gi
  bootstrap:
    initdb:
      database: productsvc
      owner: productsvc
      secret:
        name: local-dev-postgres-productsvc-creds
  resources:
    requests:
      cpu: "125m"
      memory: "256Mi"
    limits:
      cpu: "250m"
      memory: "512Mi"
