#!/usr/bin/env bash

set -euo pipefail

common_tooling_dir=${COMMON_GO_TOOLING_DIR:?COMMON_GO_TOOLING_DIR is required}
# shellcheck source=/dev/null
source "$common_tooling_dir/test-tooling-lib.sh"
tooling_initialize go-service-tooling \
	buf protoc-gen-go protoc-gen-go-grpc golangci-lint govulncheck

fixture=$(new_fixture format-new-file)
cat >"$fixture/tooling_format_defect.go" <<'EOF'
package tooling
func formatDefect( ){}
EOF
expect_failure format-new-file format-check tooling_format_defect.go "$fixture" \
	FORMAT_FILES=tooling_format_defect.go

fixture=$(new_fixture lint-only)
cat >"$fixture/internal/config/tooling_lint_defect.go" <<'EOF'
package config

import "os"

func toolingLintDefect() {
	os.Chdir(".")
}
EOF
expect_failure lint-only lint errcheck "$fixture"

fixture=$(new_fixture test)
expect_success test-baseline test "$fixture"
cat >"$fixture/internal/config/tooling_failure_test.go" <<'EOF'
package config

import "testing"

func TestToolingControlledFailure(t *testing.T) {
	t.Fatal("controlled test failure")
}
EOF
expect_failure test test ': test] Error' "$fixture"

fixture=$(new_fixture dependency)
sed -i 's/google.golang.org\/grpc v1\.83\.2/google.golang.org\/grpc v1.84.0/' \
	"$fixture/go.mod"
expect_failure dependency check-deps 'go.mod is not synchronized with update-deps' "$fixture"

fixture=$(new_fixture proto-format)
sed -i 's/^  rpc Echo/rpc Echo/' "$fixture/api/scaffold/v1/example_service.proto"
expect_failure proto-format format-proto-check 'rpc Echo' "$fixture"

fixture=$(new_fixture proto-lint)
sed -i '0,/string message = 1/{s/string message = 1/string BadName = 1/}' \
	"$fixture/api/scaffold/v1/example_service.proto"
expect_failure proto-lint lint-proto 'should be lower_snake_case' "$fixture"

fixture=$(new_fixture proto-breaking)
sed -i '/message EchoResponse {/,/}/ s/string message = 1;/string message = 2;/' \
	"$fixture/api/scaffold/v1/example_service.proto"
expect_failure proto-breaking check-proto-breaking 'Previously present field "1"' "$fixture"

fixture=$(new_fixture generated-modified)
printf '\n// controlled drift\n' >>"$fixture/gen/scaffold/v1/example_service.pb.go"
expect_failure generated-modified check-proto-drift \
	'generated output differs from regeneration' "$fixture"

fixture=$(new_fixture generated-unexpected)
printf 'controlled unexpected output\n' >"$fixture/gen/scaffold/v1/unexpected.txt"
expect_failure generated-unexpected check-proto-drift \
	'unexpected output in generated tree' "$fixture"

fixture=$(new_fixture generated-missing)
rm -- "$fixture/gen/scaffold/v1/example_service_grpc.pb.go"
expect_failure generated-missing check-proto-drift 'missing expected output' "$fixture"

fixture=$(new_fixture generated-stale)
cat >"$fixture/gen/scaffold/v1/removed_service.pb.go" <<'EOF'
// Code generated by controlled tooling test. DO NOT EDIT.

package scaffoldv1
EOF
expect_failure generated-stale check-proto-drift \
	'stale generated output is no longer declared' "$fixture"

printf 'test-tooling: all controlled failures were rejected without fixture mutation\n'
