micronaut:
  server:
    host: localhost
    port: 8088
---
mongodb:
  uri: "mongodb://product:mongoProductUserPwd@localhost:27017/products-demo"
---
products:
  persistence: mongo
---
postgres:
  host: localhost
  port: 5432
  database: product
  username: product
  password: product
  ssl: false
---
# This is only to allow Micronaut to bootstrap DataSource;
# overridden at runtime by PostgresDatasourceConfigurationListener#onCreated(BeanCreatedEvent<DatasourceConfiguration>)
datasources:
  default:
    driverClassName: org.postgresql.Driver
    url: "jdbc:postgresql://localhost:5432/product"
    username: product
    password: product
---
jpa:
  default:
    packages-to-scan:
      - 'pl.altkom.asc.lab.micronaut.poc.product.service.infrastructure.adapters.db.model'
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: false
tracing:
  zipkin:
    enabled: false
