// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package dbgen

import (
	"context"
)

const getProduct = `-- name: GetProduct :one
SELECT code, definition
FROM public.product
WHERE code = $1
`

func (q *Queries) GetProduct(ctx context.Context, code string) (Product, error) {
	row := q.db.QueryRow(ctx, getProduct, code)
	var i Product
	err := row.Scan(&i.Code, &i.Definition)
	return i, err
}

const listProducts = `-- name: ListProducts :many
SELECT code, definition
FROM public.product
`

func (q *Queries) ListProducts(ctx context.Context) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(&i.Code, &i.Definition); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
