apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-vue-legacy
spec:
  template:
    spec:
      containers:
        - name: web-vue-legacy
          image: ghcr.io/igor-baiborodine/insurance-hub/web-vue-legacy:1.0.0
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 300m
              memory: 512Mi