apiVersion: apps/v1
kind: Deployment
metadata:
  name: jsreport
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jsreport
  template:
    metadata:
      labels:
        app: jsreport
    spec:
      containers:
        - name: jsreport
          image: jsreport/jsreport:4.10.1
          ports:
            - containerPort: 5488
          volumeMounts:
            - name: jsreport-cache
              mountPath: /app/data
          env:
            - name: NODE_ENV
              value: production
          readinessProbe:
            httpGet:
              path: /
              port: 5488
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 5488
            initialDelaySeconds: 30
            periodSeconds: 10
      volumes:
        - name: jsreport-cache
          persistentVolumeClaim:
            claimName: jsreport-cache-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: jsreport
spec:
  selector:
    app: jsreport
  ports:
    - name: http
      port: 5488
      targetPort: 5488
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jsreport-cache-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: jsreport-config
data:
  licenseKey: ""
  # Additional JSReport configuration if required
